<?php

namespace DoctrineProxies\__CG__\App\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \App\Model\Post implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Model\\Post' . "\0" . 'id', '' . "\0" . 'App\\Model\\Post' . "\0" . 'title', '' . "\0" . 'App\\Model\\Post' . "\0" . 'description', '' . "\0" . 'App\\Model\\Post' . "\0" . 'image', '' . "\0" . 'App\\Model\\Post' . "\0" . 'posted_at', '' . "\0" . 'App\\Model\\Post' . "\0" . 'comments_num', '' . "\0" . 'App\\Model\\Post' . "\0" . 'associated_likes', '' . "\0" . 'App\\Model\\Post' . "\0" . 'user'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Model\\Post' . "\0" . 'id', '' . "\0" . 'App\\Model\\Post' . "\0" . 'title', '' . "\0" . 'App\\Model\\Post' . "\0" . 'description', '' . "\0" . 'App\\Model\\Post' . "\0" . 'image', '' . "\0" . 'App\\Model\\Post' . "\0" . 'posted_at', '' . "\0" . 'App\\Model\\Post' . "\0" . 'comments_num', '' . "\0" . 'App\\Model\\Post' . "\0" . 'associated_likes', '' . "\0" . 'App\\Model\\Post' . "\0" . 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Post $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostedAt($postedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostedAt', [$postedAt]);

        return parent::setPostedAt($postedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostedAt', []);

        return parent::getPostedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentsNum($commentsNum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentsNum', [$commentsNum]);

        return parent::setCommentsNum($commentsNum);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentsNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentsNum', []);

        return parent::getCommentsNum();
    }

    /**
     * {@inheritDoc}
     */
    public function addAssociatedLike(\App\Model\Like $associatedLike)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAssociatedLike', [$associatedLike]);

        return parent::addAssociatedLike($associatedLike);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAssociatedLike(\App\Model\Like $associatedLike)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAssociatedLike', [$associatedLike]);

        return parent::removeAssociatedLike($associatedLike);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssociatedLikes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssociatedLikes', []);

        return parent::getAssociatedLikes();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\App\Model\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function isLikedByUser(\App\Model\User $user): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLikedByUser', [$user]);

        return parent::isLikedByUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumLikes(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumLikes', []);

        return parent::getNumLikes();
    }

}
