<?php

namespace App\Model;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

  /**
   * Retrieves an array graph (a nested array) for comments
   * related to the post
   */
  public function getCommentsArrayByPost(Post $o_post, int $n_num = null, int $n_offset = 0) : array
  {
    return $this->getCommentsByPostId($o_post->getId(), $n_num, $n_offset); // Retrieves a collection of objects
  }//end of function


  /**
   * Retrieves an array graph (a nested array) for comments
   * related to the post
   */
  public function getCommentsArrayByPostId(int $postId, int $n_num = null, int $n_offset = 0) : array
  {
    $c_dql = <<<DQL
SELECT c, u FROM App\Model\Comment c JOIN c.user u
WHERE c.post = :post_id
DQL;
    $o_query = $this->_em->createQuery($c_dql)
      ->setParameter('post_id', $postId);

    if ($n_num) $o_query->setMaxResults($n_num);
    if ($n_offset) $o_query->setFirstResult($n_offset);

    return $o_query->getArrayResult(); // Retrieves an array graph (a nested array)
  }//end of function




  /**
   *
   */
  public function deleteCommentById(int $commentId)
  {
    $c_dql = <<<DQL
DELETE FROM App\Model\Comment c WHERE c.id = :comment_id
DQL;
    $o_query = $this->_em->createQuery($c_dql)
      ->setParameter('comment_id', $commentId);
    return $o_query->execute();
  }//end of function


}// end of class
