<?php

namespace App\Model;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

  /**
   *
   */
   public function getUserById(int $user_id) : User
   {
     if (empty($user_id)) throw new \InvalidArgumentException('Пустой идентификатор пользователя в методе ' . __METHOD__);

     return $this->findOneById($user_id);
   }//end of function


  /**
   *
   */
  public function getUsersBatchArray($n_start_index, $n_max_per_page, $c_sorting_params)
  {
    // Сортировка элементов в запросе к базе данных
    $c_sorting_order_clause = 'u.id ASC'; // значение по умолчанию
    if (!empty($c_sorting_params)) {
      // пересобрать часть entity + порядок сортировки для запроса
      // так как я не нашёл способа безопасно вставить данные из AJAX запроса в query
      $a_sorting_parts = explode(' ', $c_sorting_params, 2);
      $c_sorting_order = $a_sorting_parts[0];
      $c_sorting_order_field = ['email' => 'u.email', 'role' => 'u.role', 'id' => 'u.id'][$c_sorting_order] ?? 'u.id' ;
      $c_sorting_order_asc = $a_sorting_parts[1] ?? 'ASC';
      $c_sorting_order_clause = $c_sorting_order_field .  ' ' . $c_sorting_order_asc;
    }//endif

      // Получить массив объектов пользователей
      $c_dql = 'SELECT u.id, u.email, u.name, u.role  FROM App\Model\User u ORDER BY ' . $c_sorting_order_clause;
      //
      $a_users_array = $this->_em->createQuery($c_dql)
        ->setFirstResult($n_start_index)
        ->setMaxResults($n_max_per_page)
        ->getArrayResult();

        return $a_users_array;
  }//end of function


  /**
   *
   */
  public function getTotalUsersCount() : int
  {
    // Получить цифру - количество пользователей
    // Query::HYDRATE_SINGLE_SCALAR mode
    $c_dql = 'SELECT COUNT(u.id) FROM App\Model\User u';
    $n_total_records_count = $this->_em->createQuery($c_dql)
      ->getSingleScalarResult();

    return (int) $n_total_records_count;
  }//end of funciton






}//end of class
